### ISSUE TITLE
setLetter crashes (java.lang.StringIndexOutOfBoundsException) when argument is a string that only contains spaces

### ISSUE THREAD

**Issue by isidro89** [IvBaranov/MaterialLetterIcon#14]
Stack trace:
java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=1
        at java.lang.String.substring(String.java:1931)
        at com.github.ivbaranov.mli.MaterialLetterIcon.setLetter(MaterialLetterIcon.java:358)
       ...

**Comment by IvBaranov** [comment]
Thanks for pointing out.
