### ISSUE TITLE
Unable to add id attribute

### ISSUE THREAD

**Issue by engineersAtEdutrace** [IvBaranov/MaterialLetterIcon#9]
<com.github.ivbaranov.mli.MaterialLetterIcon
            android:layout_width="30dp"
            android:layout_height="30dp"
            android:id="@+id/letterIcon"/>

With this code program is throwing error but works fine without Id attribute

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fantasticfive.shareback/com.fantasticfive.shareback.newshareback.activities.NewMainActivity}: java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to android.widget.ImageView
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                                                 at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                              Caused by: java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to android.widget.ImageView
                                                                                 at com.mingle.widget.LoadingView.onFinishInflate(LoadingView.java:97)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:814)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)

**Comment by IvBaranov** [comment]
Make sure your layout looks like this:
```
<com.github.ivbaranov.mli.MaterialLetterIcon
        android:id="@+id/icon"
        android:layout_width="@dimen/list_item_avatar_size"
        android:layout_height="@dimen/list_item_avatar_size"
        android:layout_marginRight="16dp" />
```
while in code:
`MaterialLetterIcon mIcon = (MaterialLetterIcon) view.findViewById(R.id.icon);`

`java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to android.widget.ImageView`
means you are either casting **MaterialLetterIcon** to **AppCompatTextView**, or using wrong tag in layout file.

**Comment by engineersAtEdutrace** [comment]
**This works perfectly**
<com.github.ivbaranov.mli.MaterialLetterIcon
        android:id="@+id/icon"
        android:layout_width="@dimen/list_item_avatar_size"
        android:layout_height="@dimen/list_item_avatar_size"
        android:layout_marginRight="16dp" />

**While this gives error**
<com.github.ivbaranov.mli.MaterialLetterIcon
            android:id="@+id/letterIcon"
            android:layout_width="30dp"
            android:layout_height="30dp"
            android:layout_marginRight="16dp" />

**Comment by IvBaranov** [comment]
I am sure you should check your casts in code and tags in layout file as I wrote above.
